version: '2'

services:
  db:
    image: 'postgres:17.4-alpine'
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pwd
  solr:
    image: 'solr:9.8.0'
    ports:
      - "8983:8983"
    command:
      - solr-precreate
      - games
      - /config
    volumes:
      - ./src/main/solr:/config/conf
volumes:
  solr-data:
  db-data: