version: '2'

services:
  db:
    image: 'postgres:17.4-alpine'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pwd
  # TODO Implement search
  #solr:
  #  image: 'solr:9.8.0'
  #  ports:
  #      - "8983:8983"
  #  command:
  #   - solr-precreate
  #   - games
  #  #Uncomment to use a custom configuration
  #  #volumes:
  #  #  - ./src/main/solr/managed-schema.xml:/opt/solr/server/solr/configsets/_default/conf/managed-schema.xml
